/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Departments */
        get: operations["departments_api_departments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description Held documents for the caller's department (soonest deadline first), then its open disputes.
         */
        get: operations["review_queue_api_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library */
        get: operations["library_api_documents_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Submissions */
        get: operations["my_submissions_api_documents_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Escalations */
        get: operations["escalations_api_escalations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Departments publish their own documents; contributors submit one for a department's review.
         */
        post: operations["upload_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File Link */
        get: operations["file_link_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/resubmit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resubmit
         * @description Send a revised file back to the department after a dispute (once per document).
         */
        post: operations["resubmit_api_documents__document_id__resubmit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Action
         * @description accept or dispute (department), accept-dispute or escalate (contributor), uphold or overrule (MCE).
         */
        post: operations["take_action_api_documents__document_id___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/publish-expired": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Expired */
        post: operations["publish_expired_api_jobs_publish_expired_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "accept" | "dispute" | "accept-dispute" | "resubmit" | "escalate" | "uphold" | "overrule";
        /** ActionRequest */
        ActionRequest: {
            /** Note */
            note?: string | null;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["AskSource"][];
        };
        /** AskSource */
        AskSource: {
            /** Label */
            label: string;
            /** Cited */
            cited: boolean;
            /** Document Id */
            document_id: string;
            /** Title */
            title: string | null;
            /** Chunk Text */
            chunk_text: string;
            /** Department */
            department: string | null;
            /** Source Type */
            source_type: string | null;
            /** Published At */
            published_at: string | null;
            /** Document Year */
            document_year: number | null;
        };
        /** Body_resubmit_api_documents__document_id__resubmit_post */
        Body_resubmit_api_documents__document_id__resubmit_post: {
            /**
             * File
             * @description The revised PDF
             */
            file: string;
            /** Note */
            note?: string | null;
        };
        /** Body_upload_api_documents_post */
        Body_upload_api_documents_post: {
            /**
             * File
             * @description The document, as a PDF of at most 50 MB
             */
            file: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Document Year */
            document_year?: string | null;
            /**
             * Department
             * @description Contributors only: the department it belongs to
             */
            department?: string | null;
            /**
             * Source Url
             * @description Required from contributors
             */
            source_url?: string | null;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Department */
            department: string;
            /** Department Name */
            department_name: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url: string | null;
            /** Document Year */
            document_year: number | null;
            status: components["schemas"]["LedgerStatus"];
            /** Uploaded By */
            uploaded_by: string;
            /** Uploaded By Name */
            uploaded_by_name: string | null;
            /** Created At */
            created_at: string;
            /** Published At */
            published_at: string | null;
            /** Held Until */
            held_until: string | null;
            /** Escalated To Mce */
            escalated_to_mce: boolean;
            /** Dispute Reason */
            dispute_reason: string | null;
            /** Disputed By Name */
            disputed_by_name: string | null;
            /** Disputed At */
            disputed_at: string | null;
            /** Contributor Response */
            contributor_response: string | null;
            /** Resubmission Count */
            resubmission_count: number;
            ingestion: components["schemas"]["IngestionState"] | null;
            /** Chunk Count */
            chunk_count: number | null;
            /** Allowed Actions */
            allowed_actions: components["schemas"]["Action"][];
            /** History */
            history: components["schemas"]["HistoryEntryOut"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Department */
            department: string;
            /** Department Name */
            department_name: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url: string | null;
            /** Document Year */
            document_year: number | null;
            status: components["schemas"]["LedgerStatus"];
            /** Uploaded By */
            uploaded_by: string;
            /** Uploaded By Name */
            uploaded_by_name: string | null;
            /** Created At */
            created_at: string;
            /** Published At */
            published_at: string | null;
            /** Held Until */
            held_until: string | null;
            /** Escalated To Mce */
            escalated_to_mce: boolean;
            /** Dispute Reason */
            dispute_reason: string | null;
            /** Disputed By Name */
            disputed_by_name: string | null;
            /** Disputed At */
            disputed_at: string | null;
            /** Contributor Response */
            contributor_response: string | null;
            /** Resubmission Count */
            resubmission_count: number;
            ingestion: components["schemas"]["IngestionState"] | null;
            /** Chunk Count */
            chunk_count: number | null;
            /** Allowed Actions */
            allowed_actions: components["schemas"]["Action"][];
        };
        /** DocumentPage */
        DocumentPage: {
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /** Total */
            total: number;
        };
        /** FileLink */
        FileLink: {
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryAction
         * @enum {string}
         */
        HistoryAction: "uploaded" | "submitted" | "accepted" | "disputed" | "dispute_accepted" | "resubmitted" | "escalated" | "upheld" | "overruled" | "auto_published";
        /** HistoryEntryOut */
        HistoryEntryOut: {
            action: components["schemas"]["HistoryAction"];
            /** Actor Name */
            actor_name: string;
            /** Actor Role */
            actor_role: string;
            from_status: components["schemas"]["LedgerStatus"] | null;
            to_status: components["schemas"]["LedgerStatus"];
            /** Note */
            note: string | null;
            /** At */
            at: string;
        };
        /**
         * IngestionState
         * @enum {string}
         */
        IngestionState: "processing" | "searchable" | "not_searchable" | "failed";
        /** JobResult */
        JobResult: {
            /** Published */
            published: string[];
            /** Ingestion Queued */
            ingestion_queued: string[];
        };
        /**
         * LedgerStatus
         * @enum {string}
         */
        LedgerStatus: "held" | "published" | "disputed" | "withdrawn";
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /** Department */
            department: string | null;
            /** Department Name */
            department_name: string | null;
        };
        /** Option */
        Option: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "department" | "contributor" | "mce";
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "agency" | "contributor";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    departments_api_departments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Option"][];
                };
            };
        };
    };
    categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Option"][];
                };
            };
        };
    };
    review_queue_api_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    library_api_documents_library_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_submissions_api_documents_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    escalations_api_escalations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    upload_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_link_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resubmit_api_documents__document_id__resubmit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_resubmit_api_documents__document_id__resubmit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_action_api_documents__document_id___action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                action: components["schemas"]["Action"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_expired_api_jobs_publish_expired_post: {
        parameters: {
            query?: never;
            header?: {
                "x-job-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
