/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Stream */
        post: operations["ask_stream_api_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Published File
         * @description Redirects to a fresh 10-minute link to a published document's PDF; 404 for anything else.
         */
        get: operations["published_file_api_ledger__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Departments */
        get: operations["departments_api_departments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description Held documents for the caller's department (soonest deadline first), then its open disputes.
         */
        get: operations["review_queue_api_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library */
        get: operations["library_api_documents_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Submissions */
        get: operations["my_submissions_api_documents_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Escalations */
        get: operations["escalations_api_escalations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Departments publish their own documents; contributors submit one for a department's review.
         */
        post: operations["upload_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File Link */
        get: operations["file_link_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/resubmit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resubmit
         * @description Send a revised file back to the department after a dispute (once per document).
         */
        post: operations["resubmit_api_documents__document_id__resubmit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Action
         * @description accept or dispute (department), accept-dispute or escalate (contributor), uphold or overrule (MCE).
         */
        post: operations["take_action_api_documents__document_id___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/publish-expired": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Expired */
        post: operations["publish_expired_api_jobs_publish_expired_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_reports_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** File Report */
        post: operations["file_report_api_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{reference}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_reports__reference__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{reference}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate */
        post: operations["escalate_api_reports__reference__escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{reference}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preferences */
        post: operations["preferences_api_reports__reference__preferences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue */
        get: operations["queue_api_cases_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/oversight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oversight */
        get: operations["oversight_api_cases_oversight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Case */
        get: operations["case_api_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_api_cases__case_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve */
        post: operations["resolve_api_cases__case_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/reassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reassign */
        post: operations["reassign_api_cases__case_id__reassign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen */
        post: operations["reopen_api_cases__case_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/confirm-resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Resolution */
        post: operations["confirm_resolution_api_cases__case_id__confirm_resolution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cases/{case_id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shared Location
         * @description Opened on purpose, never listed: the view goes to the audit trail and to the citizen's status page.
         */
        get: operations["shared_location_api_cases__case_id__location_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Directory */
        get: operations["directory_api_contacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/representatives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Representatives */
        get: operations["representatives_api_representatives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issues */
        get: operations["issues_api_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues/{public_id}/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Voice */
        post: operations["add_voice_api_issues__public_id__voices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/sms/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sms Delivery
         * @description Record whether an SMS reached the phone. Unsigned, stale or forged reports are refused.
         *
         *     A report is idempotent (it sets the row's delivery status), so a repeat of a
         *     valid one changes nothing and needs no duplicate check.
         */
        get: operations["sms_delivery_api_channels_sms_delivery_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/ussd/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ussd Session
         * @description The next screen. Arkesel doesn't sign USSD callbacks yet, so the URL's secret is the only check:
         *     a wrong one looks like no route at all.
         */
        post: operations["ussd_session_api_channels_ussd__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whatsapp Message
         * @description Twilio gets an empty answer at once; the reply (an answer can take 13 seconds) follows by the API.
         */
        post: operations["whatsapp_message_api_channels_whatsapp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/whatsapp/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whatsapp Status
         * @description A WhatsApp message's delivery; one refused because WhatsApp's window had closed goes by SMS instead.
         */
        post: operations["whatsapp_status_api_channels_whatsapp_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "accept" | "dispute" | "accept-dispute" | "resubmit" | "escalate" | "uphold" | "overrule";
        /** ActionRequest */
        ActionRequest: {
            /** Note */
            note?: string | null;
        };
        /**
         * AskFigure
         * @description A live count of reports residents filed with Nokware: a source, but not a document.
         */
        AskFigure: {
            /** Label */
            label: string;
            /** Cited */
            cited: boolean;
            /** Description */
            description: string;
            /** Value */
            value: string;
            /** Rows */
            rows: components["schemas"]["FigureRow"][];
            /** Counted At */
            counted_at: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "no_information";
            /** Sources */
            sources: components["schemas"]["AskSource"][];
            /** Figures */
            figures: components["schemas"]["AskFigure"][];
        };
        /**
         * AskSource
         * @description One retrieved chunk; a document's chunks share its label.
         */
        AskSource: {
            /** Label */
            label: string;
            /** Cited */
            cited: boolean;
            /** Document Id */
            document_id: string;
            /** Title */
            title: string | null;
            /** Chunk Text */
            chunk_text: string;
            /** Department */
            department: string | null;
            /** Department Name */
            department_name: string | null;
            /** Source Type */
            source_type: string | null;
            provenance: components["schemas"]["Provenance"] | null;
            /** Source Url */
            source_url: string | null;
            /** Published At */
            published_at: string | null;
            /** Document Year */
            document_year: number | null;
        };
        /**
         * AskStreamEvent
         * @description One line of POST /api/ask/stream's newline-delimited JSON.
         */
        AskStreamEvent: components["schemas"]["StageEvent"] | components["schemas"]["SourcesEvent"] | components["schemas"]["DeltaEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["ErrorEvent"];
        /** Body_file_report_api_reports_post */
        Body_file_report_api_reports_post: {
            /**
             * Photos
             * @description Up to 10 JPEG, PNG or WebP photos.
             * @default []
             */
            photos: string[];
            /** Description */
            description: string;
            /** Ward */
            ward?: string | null;
            /** Sub Metro */
            sub_metro?: string | null;
            /**
             * Safety Topic
             * @description Set only by the personal-safety form.
             */
            safety_topic?: string | null;
            /** Phone */
            phone?: string | null;
            /** Whatsapp */
            whatsapp?: string | null;
            /**
             * Notify
             * @description Safety form: the citizen's opt-in to messages.
             * @default false
             */
            notify: boolean;
            /**
             * Callback Consent
             * @description Safety form: Police and Social Welfare may call.
             * @default false
             */
            callback_consent: boolean;
        };
        /** Body_resubmit_api_documents__document_id__resubmit_post */
        Body_resubmit_api_documents__document_id__resubmit_post: {
            /**
             * File
             * @description The revised PDF
             */
            file: string;
            /** Note */
            note?: string | null;
        };
        /** Body_upload_api_documents_post */
        Body_upload_api_documents_post: {
            /**
             * File
             * @description The document, as a PDF of at most 50 MB
             */
            file: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Document Year */
            document_year?: string | null;
            /**
             * Department
             * @description Contributors only: the department it belongs to
             */
            department?: string | null;
            /**
             * Source Url
             * @description Required from contributors
             */
            source_url?: string | null;
        };
        /**
         * CaseAction
         * @enum {string}
         */
        CaseAction: "acknowledge" | "resolve" | "reassign" | "reopen" | "confirm-resolution";
        /** CaseAssignment */
        CaseAssignment: {
            /** Recipient */
            recipient: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Active */
            active: boolean;
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Resolution Note */
            resolution_note: string | null;
        };
        /** CaseDetail */
        CaseDetail: {
            /** Case Id */
            case_id: string;
            /** Reference */
            reference: string;
            /** Private */
            private: boolean;
            /**
             * View
             * @enum {string}
             */
            view: "full" | "oversight";
            /** Topic */
            topic: string;
            /** Severity */
            severity: number;
            /** Status */
            status: string;
            /** My Status */
            my_status: string | null;
            /** Place */
            place: string | null;
            /** Excerpt */
            excerpt: string | null;
            /** Submitted At */
            submitted_at: string;
            /** Recipients */
            recipients: string[];
            /** Escalated */
            escalated: boolean;
            /** Needs Routing */
            needs_routing: boolean;
            /** Allowed Actions */
            allowed_actions: components["schemas"]["CaseAction"][];
            /** Voices */
            voices: number;
            /** Description */
            description: string | null;
            /** Photos */
            photos: string[];
            /** Escalation Note */
            escalation_note: string | null;
            /** Classification Note */
            classification_note: string | null;
            contact: components["schemas"]["Contact"] | null;
            /** Assignments */
            assignments: components["schemas"]["CaseAssignment"][];
            /** History */
            history: components["schemas"]["CaseEvent"][];
            /** Voice Names */
            voice_names: string[] | null;
            /** Location Shared At */
            location_shared_at?: string | null;
        };
        /** CaseEvent */
        CaseEvent: {
            /** Action */
            action: string;
            /** Actor Name */
            actor_name: string;
            /** Actor Role */
            actor_role: string;
            /** Note */
            note: string | null;
            /** At */
            at: string;
        };
        /** CaseOversight */
        CaseOversight: {
            /** Cases */
            cases: components["schemas"]["CaseSummary"][];
            stats: components["schemas"]["OversightStats"];
            /** Recipients */
            recipients: components["schemas"]["Option"][];
        };
        /** CaseQueue */
        CaseQueue: {
            /** Cases */
            cases: components["schemas"]["CaseSummary"][];
        };
        /** CaseSummary */
        CaseSummary: {
            /** Case Id */
            case_id: string;
            /** Reference */
            reference: string;
            /** Private */
            private: boolean;
            /**
             * View
             * @enum {string}
             */
            view: "full" | "oversight";
            /** Topic */
            topic: string;
            /** Severity */
            severity: number;
            /** Status */
            status: string;
            /** My Status */
            my_status: string | null;
            /** Place */
            place: string | null;
            /** Excerpt */
            excerpt: string | null;
            /** Submitted At */
            submitted_at: string;
            /** Recipients */
            recipients: string[];
            /** Escalated */
            escalated: boolean;
            /** Needs Routing */
            needs_routing: boolean;
            /** Allowed Actions */
            allowed_actions: components["schemas"]["CaseAction"][];
            /** Voices */
            voices: number;
        };
        /**
         * Contact
         * @description Shown only to a case's recipients, and only when the citizen allowed a call.
         */
        Contact: {
            /** Phone */
            phone: string | null;
            /** Whatsapp */
            whatsapp: string | null;
        };
        /** ContactDirectory */
        ContactDirectory: {
            /** About */
            about: string;
            /** Checked */
            checked: string;
            /** Services */
            services: components["schemas"]["Service"][];
        };
        /** ContactNumber */
        ContactNumber: {
            /** Number */
            number: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "call" | "whatsapp";
            /**
             * Current
             * @default true
             */
            current: boolean;
            /** Note */
            note?: string | null;
        };
        /** ContactSource */
        ContactSource: {
            /** Label */
            label: string;
            /** Url */
            url: string;
            /** Checked */
            checked: string;
        };
        /** Dashboard */
        Dashboard: {
            /** Generated At */
            generated_at: string;
            /** Period Start */
            period_start: string;
            /** Received */
            received: number | null;
            /** Resolved */
            resolved: number | null;
            /** Median Days */
            median_days: number | null;
            /** Months */
            months: components["schemas"]["MonthFigures"][];
            /** Topics */
            topics: components["schemas"]["TopicFigures"][];
            /** Sub Metros */
            sub_metros: components["schemas"]["SubMetroFigures"][];
            /** Documents Published */
            documents_published: number;
            /** Departments Publishing */
            departments_publishing: number;
            /** Recent Documents */
            recent_documents: components["schemas"]["RecentDocument"][];
        };
        /**
         * DeltaEvent
         * @description The next piece of the model's raw answer text.
         */
        DeltaEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "delta";
            /** Text */
            text: string;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Department */
            department: string;
            /** Department Name */
            department_name: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url: string | null;
            /** Document Year */
            document_year: number | null;
            status: components["schemas"]["LedgerStatus"];
            /** Uploaded By */
            uploaded_by: string;
            /** Uploaded By Name */
            uploaded_by_name: string | null;
            /** Created At */
            created_at: string;
            /** Published At */
            published_at: string | null;
            /** Held Until */
            held_until: string | null;
            /** Escalated To Mce */
            escalated_to_mce: boolean;
            /** Dispute Reason */
            dispute_reason: string | null;
            /** Disputed By Name */
            disputed_by_name: string | null;
            /** Disputed At */
            disputed_at: string | null;
            /** Contributor Response */
            contributor_response: string | null;
            /** Resubmission Count */
            resubmission_count: number;
            ingestion: components["schemas"]["IngestionState"] | null;
            /** Chunk Count */
            chunk_count: number | null;
            /** Allowed Actions */
            allowed_actions: components["schemas"]["Action"][];
            /** History */
            history: components["schemas"]["HistoryEntryOut"][];
        };
        /** DocumentOut */
        DocumentOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Department */
            department: string;
            /** Department Name */
            department_name: string | null;
            source_type: components["schemas"]["SourceType"];
            /** Source Url */
            source_url: string | null;
            /** Document Year */
            document_year: number | null;
            status: components["schemas"]["LedgerStatus"];
            /** Uploaded By */
            uploaded_by: string;
            /** Uploaded By Name */
            uploaded_by_name: string | null;
            /** Created At */
            created_at: string;
            /** Published At */
            published_at: string | null;
            /** Held Until */
            held_until: string | null;
            /** Escalated To Mce */
            escalated_to_mce: boolean;
            /** Dispute Reason */
            dispute_reason: string | null;
            /** Disputed By Name */
            disputed_by_name: string | null;
            /** Disputed At */
            disputed_at: string | null;
            /** Contributor Response */
            contributor_response: string | null;
            /** Resubmission Count */
            resubmission_count: number;
            ingestion: components["schemas"]["IngestionState"] | null;
            /** Chunk Count */
            chunk_count: number | null;
            /** Allowed Actions */
            allowed_actions: components["schemas"]["Action"][];
        };
        /** DocumentPage */
        DocumentPage: {
            /** Documents */
            documents: components["schemas"]["DocumentOut"][];
            /** Total */
            total: number;
        };
        /**
         * DoneEvent
         * @description The checked answer, which replaces the streamed text, and the labels it cites.
         */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            /** Answer */
            answer: string;
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "no_information";
            /** Cited */
            cited: string[];
        };
        /** ElectoralArea */
        ElectoralArea: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Alternates */
            alternates: string[];
            /** Note */
            note?: string | null;
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** EscalationRequest */
        EscalationRequest: {
            /** Note */
            note: string;
        };
        /** FigureRow */
        FigureRow: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** FileLink */
        FileLink: {
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryAction
         * @enum {string}
         */
        HistoryAction: "uploaded" | "submitted" | "accepted" | "disputed" | "dispute_accepted" | "resubmitted" | "escalated" | "upheld" | "overruled" | "auto_published";
        /** HistoryEntryOut */
        HistoryEntryOut: {
            action: components["schemas"]["HistoryAction"];
            /** Actor Name */
            actor_name: string;
            /** Actor Role */
            actor_role: string;
            from_status: components["schemas"]["LedgerStatus"] | null;
            to_status: components["schemas"]["LedgerStatus"];
            /** Note */
            note: string | null;
            /** At */
            at: string;
        };
        /**
         * IngestionState
         * @enum {string}
         */
        IngestionState: "processing" | "searchable" | "not_searchable" | "failed";
        /** Issue */
        Issue: {
            /** Public Id */
            public_id: string;
            /** Topic */
            topic: string;
            /** Ward */
            ward: string | null;
            /** Sub Metro */
            sub_metro: string | null;
            /** Departments */
            departments: string[];
            /**
             * Stage
             * @enum {string}
             */
            stage: "received" | "in_progress" | "escalated";
            /** Filed At */
            filed_at: string;
            /** Voices */
            voices: number;
        };
        /** IssuePage */
        IssuePage: {
            /** Issues */
            issues: components["schemas"]["Issue"][];
            /** Total */
            total: number;
            /** Topics */
            topics: components["schemas"]["Option"][];
            /** Sub Metros */
            sub_metros: components["schemas"]["Option"][];
        };
        /** JobResult */
        JobResult: {
            /** Published */
            published: string[];
            /** Ingestion Queued */
            ingestion_queued: string[];
        };
        /**
         * LedgerStatus
         * @enum {string}
         */
        LedgerStatus: "held" | "published" | "disputed" | "withdrawn";
        /** LocationViewNote */
        LocationViewNote: {
            /** By */
            by: string;
            /** At */
            at: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /** Department */
            department: string | null;
            /** Department Name */
            department_name: string | null;
            /** Agency */
            agency: string | null;
            /** Agency Name */
            agency_name: string | null;
        };
        /** MonthFigures */
        MonthFigures: {
            /** Month */
            month: string;
            /** Received */
            received: number | null;
            /** Resolved */
            resolved: number | null;
        };
        /** NoteRequest */
        NoteRequest: {
            /** Note */
            note: string;
        };
        /** Option */
        Option: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** OversightStats */
        OversightStats: {
            /** Open */
            open: number;
            /** Escalated */
            escalated: number;
            /** Resolved 30 Days */
            resolved_30_days: number;
            /** Personal Safety Open */
            personal_safety_open: number | null;
        };
        /** PreferencesRequest */
        PreferencesRequest: {
            /** Notify */
            notify: boolean;
            /** Callback Consent */
            callback_consent: boolean;
        };
        /** PreferencesResult */
        PreferencesResult: {
            /** Messages On */
            messages_on: boolean;
        };
        /**
         * Provenance
         * @description Where a document came from, as Ask states it.
         * @enum {string}
         */
        Provenance: "ama_website" | "department_portal" | "contributor";
        /**
         * PublicContact
         * @description One office or line. Tier 1: a national emergency line. Tier 2: on an official site (source).
         *     Tier 3: reported on social media only (reported_via), not independently verified.
         */
        PublicContact: {
            /** Id */
            id: string;
            /** Service */
            service: string;
            /**
             * Tier
             * @enum {integer}
             */
            tier: 1 | 2 | 3;
            /** Name */
            name: string;
            /** Detail */
            detail?: string | null;
            /** Numbers */
            numbers: components["schemas"]["ContactNumber"][];
            /** Email */
            email?: string | null;
            source?: components["schemas"]["ContactSource"] | null;
            /** Reported Via */
            reported_via?: string | null;
            /** Reported By */
            reported_by?: string | null;
            /** Press Url */
            press_url?: string | null;
        };
        /** ReassignRequest */
        ReassignRequest: {
            /** From Recipient */
            from_recipient: string;
            /** To Recipient */
            to_recipient: string;
            /** Reason */
            reason: string;
        };
        /** RecentDocument */
        RecentDocument: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Department Name */
            department_name: string | null;
            /** Published At */
            published_at: string | null;
        };
        /** ReportOptions */
        ReportOptions: {
            /** Sub Metros */
            sub_metros: components["schemas"]["SubMetroOption"][];
            /** Safety Types */
            safety_types: components["schemas"]["SafetyType"][];
            /** Max Photos */
            max_photos: number;
            /** Max Photo Bytes */
            max_photo_bytes: number;
            /** Description Min */
            description_min: number;
            /** Description Max */
            description_max: number;
            /** Safety Contacts */
            safety_contacts: components["schemas"]["PublicContact"][];
        };
        /** ReportReceipt */
        ReportReceipt: {
            /** Reference */
            reference: string;
            /** Case Id */
            case_id: string;
            /** Private */
            private: boolean;
            /** Topic */
            topic: string | null;
            /** Recipients */
            recipients: string[];
            /** Messages On */
            messages_on: boolean;
            /** Held For Consent */
            held_for_consent: boolean;
            /** Preferences Token */
            preferences_token: string | null;
            /** Contacts */
            contacts: components["schemas"]["PublicContact"][];
        };
        /**
         * ReportStatus
         * @description A case's status. For personal safety, only the stage: no category, service, place or note.
         */
        ReportStatus: {
            /** Reference */
            reference: string;
            /** Case Id */
            case_id: string;
            /** Private */
            private: boolean;
            /** Submitted At */
            submitted_at: string;
            /** Escalated */
            escalated: boolean;
            /** Escalate Until */
            escalate_until: string | null;
            /** Stage */
            stage?: string | null;
            /** Status */
            status?: string | null;
            /** Topic */
            topic?: string | null;
            /** Recipients */
            recipients?: string[];
            /** Ward */
            ward?: string | null;
            /** Sub Metro */
            sub_metro?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolution Notes */
            resolution_notes?: components["schemas"]["ResolutionNote"][];
            /** Contacts */
            contacts?: components["schemas"]["PublicContact"][];
            /** Voices */
            voices?: number | null;
            /** Location Views */
            location_views?: components["schemas"]["LocationViewNote"][];
        };
        /** Representation */
        Representation: {
            source: components["schemas"]["RepresentationSource"];
            switchboard: components["schemas"]["PublicContact"];
            /** Sub Metros */
            sub_metros: components["schemas"]["SubMetroRepresentation"][];
            /** Matched */
            matched?: string | null;
        };
        /** RepresentationSource */
        RepresentationSource: {
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /** ResolutionNote */
        ResolutionNote: {
            /** Recipient */
            recipient: string;
            /** Note */
            note: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "department" | "agency" | "contributor" | "mce";
        /** SafetyType */
        SafetyType: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Guide */
            guide: string;
            /** Recipients */
            recipients: string[];
        };
        /** Service */
        Service: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Contacts */
            contacts: components["schemas"]["PublicContact"][];
        };
        /**
         * SharedLocationView
         * @description A shared location, opened on purpose. The view is recorded and the citizen is told.
         */
        SharedLocationView: {
            /** Address */
            address: string | null;
            /** Latitude */
            latitude: number | null;
            /** Longitude */
            longitude: number | null;
            /** Shared At */
            shared_at: string;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "agency" | "contributor";
        /**
         * SourcesEvent
         * @description Every source retrieved, before the answer is written; none is marked cited yet.
         */
        SourcesEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sources";
            /** Sources */
            sources: components["schemas"]["AskSource"][];
            /**
             * Figures
             * @default []
             */
            figures: components["schemas"]["AskFigure"][];
        };
        /** StageEvent */
        StageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage";
            /**
             * Stage
             * @enum {string}
             */
            stage: "searching" | "counting" | "writing";
        };
        /** SubMetroFigures */
        SubMetroFigures: {
            /** Name */
            name: string;
            /** Reports */
            reports: number | null;
            /** Resolved */
            resolved: number | null;
            /** Median Days */
            median_days: number | null;
        };
        /** SubMetroOption */
        SubMetroOption: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Wards */
            wards: components["schemas"]["Option"][];
        };
        /** SubMetroRepresentation */
        SubMetroRepresentation: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Chairperson */
            chairperson: string;
            /** Chairperson Area */
            chairperson_area: string;
            /** Office */
            office: string;
            /** Electoral Areas */
            electoral_areas: components["schemas"]["ElectoralArea"][];
        };
        /** TopicFigures */
        TopicFigures: {
            /** Label */
            label: string;
            /** Count */
            count: number | null;
        };
        /**
         * UssdRequest
         * @description Arkesel's USSD callback, as its sample application reads it.
         */
        UssdRequest: {
            /** Sessionid */
            sessionID: string;
            /**
             * Userid
             * @default
             */
            userID: string;
            /**
             * Newsession
             * @default false
             */
            newSession: boolean;
            /** Msisdn */
            msisdn: string;
            /**
             * Userdata
             * @default
             */
            userData: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceRequest */
        VoiceRequest: {
            /** Device Token */
            device_token: string;
            /** Name */
            name?: string | null;
        };
        /** VoiceResult */
        VoiceResult: {
            /** Voices */
            voices: number;
            /** Added */
            added: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Newline-delimited JSON: one AskStreamEvent per line. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskStreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    published_file_api_ledger__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    departments_api_departments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Option"][];
                };
            };
        };
    };
    categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Option"][];
                };
            };
        };
    };
    review_queue_api_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    library_api_documents_library_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_submissions_api_documents_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    escalations_api_escalations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    upload_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_link_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resubmit_api_documents__document_id__resubmit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_resubmit_api_documents__document_id__resubmit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_action_api_documents__document_id___action__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                action: components["schemas"]["Action"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_expired_api_jobs_publish_expired_post: {
        parameters: {
            query?: never;
            header?: {
                "x-job-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_api_reports_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOptions"];
                };
            };
        };
    };
    file_report_api_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_file_report_api_reports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_reports__reference__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_api_reports__reference__escalate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preferences_api_reports__reference__preferences_post: {
        parameters: {
            query?: never;
            header: {
                "X-Receipt-Token": string;
            };
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_api_cases_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseQueue"];
                };
            };
        };
    };
    oversight_api_cases_oversight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOversight"];
                };
            };
        };
    };
    case_api_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_cases__case_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_api_cases__case_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reassign_api_cases__case_id__reassign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReassignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_api_cases__case_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_resolution_api_cases__case_id__confirm_resolution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shared_location_api_cases__case_id__location_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedLocationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    directory_api_contacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactDirectory"];
                };
            };
        };
    };
    representatives_api_representatives_get: {
        parameters: {
            query?: {
                area?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Representation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issues_api_issues_get: {
        parameters: {
            query?: {
                sub_metro?: string | null;
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_voice_api_issues__public_id__voices_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sms_delivery_api_channels_sms_delivery_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    ussd_session_api_channels_ussd__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UssdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_message_api_channels_whatsapp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    whatsapp_status_api_channels_whatsapp_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
}
