// Named aliases for the API's schemas. schema.d.ts is generated from the
// backend's OpenAPI document by `npm run api:types`; never edit it by hand.
import type { components } from "@/lib/api/schema";

type Schemas = components["schemas"];

export type Me = Schemas["MeResponse"];
export type Role = Schemas["Role"];
export type Action = Schemas["Action"];
/** Actions sent as JSON; resubmit carries a file and has its own endpoint. */
export type ReviewAction = Exclude<Action, "resubmit">;
export type DocumentOut = Schemas["DocumentOut"];
export type DocumentDetail = Schemas["DocumentDetail"];
export type DocumentPage = Schemas["DocumentPage"];
export type HistoryEntry = Schemas["HistoryEntryOut"];
export type HistoryAction = Schemas["HistoryAction"];
export type IngestionState = Schemas["IngestionState"];
export type LedgerStatus = Schemas["LedgerStatus"];
export type FileLink = Schemas["FileLink"];
export type Option = Schemas["Option"];
export type AskSource = Schemas["AskSource"];
export type AskStreamEvent = Schemas["AskStreamEvent"];
export type AnswerStatus = Schemas["DoneEvent"]["status"];
export type Provenance = Schemas["Provenance"];
export type CaseSummary = Schemas["CaseSummary"];
export type CaseDetail = Schemas["CaseDetail"];
export type CaseEvent = Schemas["CaseEvent"];
export type SharedLocationView = Schemas["SharedLocationView"];
export type CaseOversight = Schemas["CaseOversight"];
export type CaseAction = Schemas["CaseAction"];
export type ReportOptions = Schemas["ReportOptions"];
export type SafetyType = Schemas["SafetyType"];
export type SubMetroOption = Schemas["SubMetroOption"];
export type ReportReceipt = Schemas["ReportReceipt"];
export type ReportStatus = Schemas["ReportStatus"];
export type LocationViewNote = Schemas["LocationViewNote"];
export type ReportTimelineEvent = Schemas["TimelineEvent"];
export type ReportPreferences = Schemas["PreferencesRequest"];
export type PreferencesResult = Schemas["PreferencesResult"];
export type Dashboard = Schemas["Dashboard"];
export type MonthFigures = Schemas["MonthFigures"];
export type TopicFigures = Schemas["TopicFigures"];
export type SubMetroFigures = Schemas["SubMetroFigures"];
export type ElectoralAreaFigures = Schemas["ElectoralAreaFigures"];
export type RecentDocument = Schemas["RecentDocument"];
export type PublicContact = Schemas["PublicContact"];
export type ContactNumber = Schemas["ContactNumber"];
export type ContactDirectory = Schemas["ContactDirectory"];
export type Representation = Schemas["Representation"];
export type SubMetroRepresentation = Schemas["SubMetroRepresentation"];
export type ElectoralArea = Schemas["ElectoralArea"];
export type AskFigure = Schemas["AskFigure"];
export type AskChart = Schemas["AskChart"];
export type PublishingRecord = Schemas["PublishingRecord"];
export type ReportingGap = Schemas["ReportingGap"];
export type UnpublishedData = Schemas["UnpublishedData"];
export type RecordRequirement = Schemas["Requirement"];
export type RecordPeriod = Schemas["RecordPeriod"];
export type RecordDocument = Schemas["RecordDocument"];
export type Responsiveness = Schemas["Responsiveness"];
export type DepartmentFigures = Schemas["DepartmentFigures"];
export type ChartValue = Schemas["ChartValue"];
export type ExportView = Schemas["ExportView"];
export type AskHeard = Schemas["AskHeard"];
export type ExportFormat = Schemas["AskExportRequest"]["format"];
export type Issue = Schemas["Issue"];
export type IssuePage = Schemas["IssuePage"];
export type VoiceResult = Schemas["VoiceResult"];
export type PetitionOptions = Schemas["PetitionOptions"];
export type PetitionCard = Schemas["PetitionCard"];
export type PetitionDetail = Schemas["PetitionDetail"];
export type PetitionPage = Schemas["PetitionPage"];
export type PetitionStatus = Schemas["PetitionCard"]["status"];
export type PetitionTimelineEntry = Schemas["TimelineEntry"];
export type PetitionVersion = Schemas["VersionEntry"];
/** A removed petition's page: the removal record, and nothing of the petition. Tell them apart on `state`. */
export type PetitionTombstone = Schemas["Tombstone"];
export type PetitionOrTombstone = PetitionDetail | PetitionTombstone;
export type PetitionRemovals = Schemas["Removals"];
export type PetitionGround = Schemas["GroundOption"]["id"];
export type PetitionGroundOption = Schemas["GroundOption"];
export type PetitionReportRequest = Schemas["ReportRequest"];
export type PetitionReportFiled = Schemas["ReportFiled"];
export type PetitionDocument = Schemas["DocumentRef"];
export type LedgerMatch = Schemas["LedgerMatch"];
export type LinkedIssue = Schemas["LinkedIssue"];
export type AreaOption = Schemas["AreaOption"];
export type OwnPetition = Schemas["OwnPetition"];
export type MyPetitions = Schemas["MyPetitions"];
export type PetitionSubmission = Schemas["SubmitRequest"];
export type PetitionEdit = Schemas["EditRequest"];
export type ScreenResult = Schemas["ScreenResult"];
/** What a reader reported, and the petition it is about: a contributor's queue, newest first. */
export type PetitionReport = Schemas["ReportedPetition"];
export type PetitionReportQueue = Schemas["ReportQueue"];
export type PetitionRemovalRequest = Schemas["RemovalRequest"];
export type PetitionDismissalOption = Schemas["DismissalOption"];
export type PetitionDismissal = Schemas["DismissRequest"]["reason"];
export type PetitionRemovalNotice = Schemas["RemovalNotice"];
export type PetitionResponseOut = Schemas["PetitionResponse"];
/** The creator's one answer to the response, under it. Null until they give it. */
export type PetitionReplyOut = Schemas["PetitionReply"];
/** One comment as a reader meets it: somebody's words, or the notice standing where a removed one's were. */
export type PetitionComment = Schemas["Comment"];
export type PetitionCommentPage = Schemas["CommentPage"];
export type PetitionCommentReportRequest = Schemas["CommentReportRequest"];
/** One department the MCE asked to answer a petition, under the department's name, and the note it wrote back. */
export type PetitionDepartmentShare = Schemas["DepartmentShare"];
/** A petition as the department it was shared with meets it, with its own note if it has written one. */
export type SharedPetition = Schemas["SharedPetition"];
export type PhoneChallenge = Schemas["ChallengeResult"];
export type PhoneChallengeStatus = Schemas["ChallengeStatus"];
export type SmsCodeSent = Schemas["SmsCodeSent"];
export type SignResult = Schemas["SignResult"];
export type MySignature = Schemas["MySignature"];
export type NamedSignatures = Schemas["NamedSignatures"];
export type AwaitingResponse = Schemas["AwaitingResponse"];
export type ResponseKind = Schemas["ResponseRequest"]["kind"];
export type PetitionResponseRequest = Schemas["ResponseRequest"];
export type PetitionFigures = Schemas["PetitionFigures"];
