// Named aliases for the API's schemas. schema.d.ts is generated from the
// backend's OpenAPI document by `npm run api:types`; never edit it by hand.
import type { components } from "@/lib/api/schema";

type Schemas = components["schemas"];

export type Me = Schemas["MeResponse"];
export type Role = Schemas["Role"];
export type Action = Schemas["Action"];
/** Actions sent as JSON; resubmit carries a file and has its own endpoint. */
export type ReviewAction = Exclude<Action, "resubmit">;
export type DocumentOut = Schemas["DocumentOut"];
export type DocumentDetail = Schemas["DocumentDetail"];
export type DocumentPage = Schemas["DocumentPage"];
export type HistoryEntry = Schemas["HistoryEntryOut"];
export type HistoryAction = Schemas["HistoryAction"];
export type IngestionState = Schemas["IngestionState"];
export type LedgerStatus = Schemas["LedgerStatus"];
export type FileLink = Schemas["FileLink"];
export type Option = Schemas["Option"];
export type AskSource = Schemas["AskSource"];
export type AskStreamEvent = Schemas["AskStreamEvent"];
export type AnswerStatus = Schemas["DoneEvent"]["status"];
export type Provenance = Schemas["Provenance"];
export type CaseSummary = Schemas["CaseSummary"];
export type CaseDetail = Schemas["CaseDetail"];
export type SharedLocationView = Schemas["SharedLocationView"];
export type CaseOversight = Schemas["CaseOversight"];
export type CaseAction = Schemas["CaseAction"];
export type ReportOptions = Schemas["ReportOptions"];
export type SafetyType = Schemas["SafetyType"];
export type SubMetroOption = Schemas["SubMetroOption"];
export type ReportReceipt = Schemas["ReportReceipt"];
export type ReportStatus = Schemas["ReportStatus"];
export type LocationViewNote = Schemas["LocationViewNote"];
export type ReportPreferences = Schemas["PreferencesRequest"];
export type PreferencesResult = Schemas["PreferencesResult"];
export type Dashboard = Schemas["Dashboard"];
export type MonthFigures = Schemas["MonthFigures"];
export type TopicFigures = Schemas["TopicFigures"];
export type SubMetroFigures = Schemas["SubMetroFigures"];
export type RecentDocument = Schemas["RecentDocument"];
export type PublicContact = Schemas["PublicContact"];
export type ContactNumber = Schemas["ContactNumber"];
export type ContactDirectory = Schemas["ContactDirectory"];
export type Representation = Schemas["Representation"];
export type SubMetroRepresentation = Schemas["SubMetroRepresentation"];
export type ElectoralArea = Schemas["ElectoralArea"];
export type AskFigure = Schemas["AskFigure"];
export type AskChart = Schemas["AskChart"];
export type PublishingRecord = Schemas["PublishingRecord"];
export type RecordRequirement = Schemas["Requirement"];
export type RecordPeriod = Schemas["RecordPeriod"];
export type RecordDocument = Schemas["RecordDocument"];
export type Responsiveness = Schemas["Responsiveness"];
export type DepartmentFigures = Schemas["DepartmentFigures"];
export type ChartValue = Schemas["ChartValue"];
export type ExportView = Schemas["ExportView"];
export type ExportFormat = Schemas["AskExportRequest"]["format"];
export type Issue = Schemas["Issue"];
export type IssuePage = Schemas["IssuePage"];
export type VoiceResult = Schemas["VoiceResult"];
