"""An Ask answer as a document to keep, laid out once for PDF, Word and CSV.

The API signs the export view with every answer, and the export route renders only a view whose signature holds:
nothing is stored, and the server can't be used to print official-looking Nokware documents with invented words.
Every page says it is machine-written and not an official AMA document, so a printout can't be passed off as an
Assembly publication.
"""

import hashlib
import hmac
import json
import re
from dataclasses import dataclass
from datetime import datetime
from typing import Any
from urllib.parse import urlsplit

from app.config import get_settings
from app.schemas.ask import AskChart, AskFigure, ExportSource, ExportView
from app.services.ask_figures import when
from app.services.citations import KINDS
from app.services.rag import NO_INFO_ANSWER

HEADER_NOTICE = ("Generated by Nokware from the Accra Metropolitan Assembly's published documents. "
                 "This is not an official AMA document.")
FOOTER_NOTICE = "Machine-written by Nokware's Ask from the sources listed. Check them before relying on it."
SUPPRESSED_KEY = ('Hatched or dashed: "fewer than 5", somewhere from 1 to 4. Nokware never shows these counts exactly, '
                  "so they are drawn as a range, not a value.")
DOCUMENT_CHART_NOTE = ("Drawn from figures read from the documents cited, each one checked against the document it "
                       "comes from; Nokware charts none it cannot check.")
BUDGET_DATA_NOTE = ("Budget figures: approved amounts read from the Assembly's published budget documents, not money "
                    "released or spent. Each says which document it is read from and how much of that document its "
                    "rows cover.")
LIVE_DATA_NOTE = ("Live report data: counts of the reports residents filed with Nokware, not figures from a published "
                  "document. Reports about someone's safety are never counted, and a count from 1 to 4 reads "
                  '"fewer than 5".')
_CITATION = re.compile(rf"\[([{KINDS}])(\d+)\]")
_BOLD = re.compile(r"\*\*(.+?)\*\*")
_BULLET = re.compile(r"^\s*[*•-]\s+(.*)$")
_NUMBERED = re.compile(r"^\s*\d+[.)]\s+(.*)$")
_HEADING = re.compile(r"^\s*#+\s*(.*)$")


def _key() -> bytes:
    return hmac.new(get_settings().appwrite_api_key.encode(), b"nokware-ask-exports", hashlib.sha256).digest()


def _signed_part(view: dict[str, Any]) -> bytes:
    unsigned = {k: v for k, v in view.items() if k != "token"}
    return json.dumps(unsigned, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def sign(view: dict[str, Any]) -> str:
    return hmac.new(_key(), _signed_part(view), hashlib.sha256).hexdigest()


def verified(view: ExportView) -> bool:
    return hmac.compare_digest(sign(view.model_dump(mode="json")), view.token)


def _ledger_url(document_id: str) -> str | None:
    base = get_settings().public_api_url.rstrip("/")
    return f"{base}/api/ledger/{document_id}/file" if base else None


def _cited_documents(sources: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """The answer's sources come a passage at a time."""
    documents: dict[str, dict[str, Any]] = {}
    for source in sources:
        if source["cited"] and source["label"] not in documents:
            documents[source["label"]] = {
                "label": source["label"], "title": source.get("title") or "Untitled document",
                "department_name": source.get("department_name"), "provenance": source.get("provenance"),
                "source_url": source.get("source_url"), "document_year": source.get("document_year"),
                "published_at": source.get("published_at"), "ledger_url": _ledger_url(source["document_id"]),
            }
    return list(documents.values())


@dataclass(frozen=True)
class Answered:
    question: str
    answer: str
    status: str
    sources: list[dict[str, Any]]  # every retrieved passage, marked cited or not
    figures: list[dict[str, Any]]  # every live figure, marked cited or not
    chart: dict[str, Any] | None
    chart_note: str | None


def export_view(answered: Answered, now: datetime) -> ExportView:
    view = {
        "question": answered.question, "answered_at": now.isoformat(), "answer": answered.answer, "status": answered.status,
        "sources": [ExportSource.model_validate(d).model_dump(mode="json") for d in _cited_documents(answered.sources)],
        "figures": [AskFigure.model_validate(f).model_dump(mode="json") for f in answered.figures if f["cited"]],
        "chart": AskChart.model_validate(answered.chart).model_dump(mode="json") if answered.chart else None,
        "chart_note": answered.chart_note,
    }
    return ExportView.model_validate({**view, "token": sign(view)})


@dataclass(frozen=True)
class Block:
    kind: str  # "heading", "paragraph", "bullet" or "numbered"
    runs: list[tuple[str, bool]]  # (text, bold)


@dataclass(frozen=True)
class Content:
    question: str
    answered: str  # "14 September 2026, 22:46 GMT"
    blocks: list[Block]
    sources: list[tuple[int, ExportSource, str | None]]  # (its [n], the document, its provenance line)
    figures: list[tuple[int, AskFigure]]  # (its [Fn], the figure)
    chart: AskChart | None
    chart_note: str | None
    no_information: str | None  # where to look next, when the Ledger had nothing


def provenance_line(source: ExportSource) -> str | None:
    """Kept in the web's words: describeProvenance in frontend/src/lib/ask/sources.ts."""
    department = source.department_name or "the Assembly"
    host = urlsplit(source.source_url).netloc.removeprefix("www.") if source.source_url else None
    if source.provenance == "ama_website":
        return f"Published by {department} on ama.gov.gh"
    if source.provenance == "department_portal":
        return f"Submitted by {department}" + (f" · Source: {host}" if host else "")
    if source.provenance == "contributor":
        return f"Verified contributor — sourced from {host}" if host else "Verified contributor"
    return None


def _numbering(answer: str, view: ExportView) -> tuple[dict[str, int], dict[str, int]]:
    """Numbered in the order the answer first cites them."""
    documents: dict[str, int] = {}
    figures: dict[str, int] = {}
    known = {s.label for s in view.sources} | {f.label for f in view.figures}
    for kind, number in _CITATION.findall(answer):
        label = f"{kind}{number}"
        if label in known:
            target = documents if kind == "S" else figures
            target.setdefault(label, len(target) + 1)
    return documents, figures


def _runs(text: str) -> list[tuple[str, bool]]:
    parts = _BOLD.split(text)
    return [(part, index % 2 == 1) for index, part in enumerate(parts) if part]


def _blocks(answer: str) -> list[Block]:
    blocks: list[Block] = []
    paragraph: list[str] = []

    def close() -> None:
        if paragraph:
            blocks.append(Block("paragraph", _runs(" ".join(paragraph))))
            paragraph.clear()

    for line in answer.splitlines():
        found = next(((kind, m[1]) for kind, pattern in (("heading", _HEADING), ("bullet", _BULLET), ("numbered", _NUMBERED))
                      if (m := pattern.match(line))), None)
        if found or not line.strip():
            close()
        if found:
            blocks.append(Block(found[0], _runs(found[1].strip())))
        elif line.strip():
            paragraph.append(line.strip())
    close()
    return blocks


def content(view: ExportView, site: str) -> Content:
    documents, figures = _numbering(view.answer, view)

    def renumber(match: re.Match[str]) -> str:
        label = f"{match[1]}{match[2]}"
        number = (documents if match[1] == "S" else figures).get(label)
        return "" if number is None else f"[{number}]" if match[1] == "S" else f"[F{number}]"

    answer = _CITATION.sub(renumber, view.answer)
    by_label = {s.label: s for s in view.sources}
    listed = [(n, by_label[label], provenance_line(by_label[label])) for label, n in documents.items()]
    counted = [(n, f) for f in view.figures if (n := figures.get(f.label))]
    rti = (f"See what the Ledger holds, or how to request a document under the Right to Information Act: {site}/ask"
           if view.status == "no_information" or answer.strip().startswith(NO_INFO_ANSWER) else None)
    return Content(view.question, when(view.answered_at), _blocks(answer), listed, counted, view.chart, view.chart_note, rti)


def filename(view: ExportView, extension: str) -> str:
    """nokware-answer-2026-09-14-what-does-the-ama-charge.pdf"""
    words = re.sub(r"[^a-z0-9]+", " ", view.question.lower()).split()[:6]
    day = view.answered_at[:10]
    return f"nokware-answer-{day}-{'-'.join(words) or 'question'}.{extension}"


def figures_heading(figures: list[tuple[int, AskFigure]]) -> str:
    """Named by what they are, so a budget answer's amounts never read as counts of residents' reports."""
    kinds = {figure.source for _, figure in figures}
    return "Budget figures" if kinds == {"documents"} else "Live figures" if kinds == {"reports"} else "Figures"


def figures_notes(figures: list[tuple[int, AskFigure]]) -> list[str]:
    kinds = {figure.source for _, figure in figures}
    return [note for kind, note in (("reports", LIVE_DATA_NOTE), ("documents", BUDGET_DATA_NOTE)) if kind in kinds]


def figure_footnote(figure: AskFigure) -> str:
    if figure.source == "documents":
        read = f"Read from {figure.document_title}" + (f" ({figure.year})" if figure.year else "")
        covers = f" These rows are {figure.coverage} of what that document states it details." if figure.coverage else ""
        return f"{read}. Approved amounts, not money released or spent.{covers}"
    return f"Counted {when(figure.counted_at or '')}."


def chart_footnote(chart: AskChart) -> str:
    if chart.source == "documents":
        return DOCUMENT_CHART_NOTE
    suppressed = any(v.low != v.high for s in chart.series for v in s.values)
    return f"Live report data, counted {when(chart.counted_at or '')}." + (f" {SUPPRESSED_KEY}" if suppressed else "")
