"""An Ask answer as a Word document (python-docx): editable, with the same notices, links and chart as the PDF.

Every page's header names Nokware and says the document is generated by Nokware
from the Assembly's published documents and is not an official AMA document; the
footer says it is machine-written and gives the page number. Text is set in the
site's fonts by name; Word substitutes its own where the reader hasn't got them.
"""

import io

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.opc.constants import RELATIONSHIP_TYPE
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor
from docx.text.paragraph import Paragraph

from app.schemas.ask import AskChart, AskFigure
from app.services import export_chart
from app.services.ask_export import FOOTER_NOTICE, HEADER_NOTICE, LIVE_DATA_NOTE, Content, chart_footnote, figure_footnote, when

INK, INK_SOFT, TEAL = RGBColor(0x17, 0x24, 0x2B), RGBColor(0x4A, 0x5A, 0x5F), RGBColor(0x1F, 0x6F, 0x5C)
BODY_FONT, HEADING_FONT = "Public Sans", "Fraunces"


def _styles(document: Document) -> None:
    normal = document.styles["Normal"]
    normal.font.name, normal.font.size, normal.font.color.rgb = BODY_FONT, Pt(10.5), INK
    for name, size in (("Title", 18), ("Heading 1", 14), ("Heading 2", 12)):
        style = document.styles[name]
        style.font.name, style.font.size, style.font.color.rgb, style.font.bold = HEADING_FONT, Pt(size), INK, False
        style.paragraph_format.keep_with_next = True


def _small(paragraph: Paragraph, text: str, bold: bool = False) -> None:
    run = paragraph.add_run(text)
    run.font.size, run.font.color.rgb, run.bold = Pt(8.5), INK_SOFT, bold


def _page_number(paragraph: Paragraph) -> None:
    """A PAGE field, which Word fills in on each page."""
    run = paragraph.add_run()
    for kind, text in (("begin", None), (None, "PAGE"), ("end", None)):
        element = OxmlElement("w:fldChar" if kind else "w:instrText")
        if kind:
            element.set(qn("w:fldCharType"), kind)
        else:
            element.set(qn("xml:space"), "preserve")
            element.text = text
        run._r.append(element)
    run.font.size, run.font.color.rgb = Pt(8), INK_SOFT


def _frame(document: Document) -> None:
    section = document.sections[0]
    section.left_margin = section.right_margin = Cm(2)
    header = section.header.paragraphs[0]
    mark = header.add_run("Nokware  ")
    mark.font.name, mark.font.size, mark.font.color.rgb = HEADING_FONT, Pt(13), INK
    _small(header, "Accra's public record")
    _small(section.header.add_paragraph(), HEADER_NOTICE, bold=True)
    footer = section.footer.paragraphs[0]
    _small(footer, f"{FOOTER_NOTICE}  Page ")
    _page_number(footer)


def _link(paragraph: Paragraph, url: str) -> None:
    """A clickable link: python-docx has no call for it, so the relationship and run are made by hand."""
    if not url.startswith(("https://", "http://")):
        paragraph.add_run(url)
        return
    rel = paragraph.part.relate_to(url, RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    link = OxmlElement("w:hyperlink")
    link.set(qn("r:id"), rel)
    run = OxmlElement("w:r")
    props = OxmlElement("w:rPr")
    for tag, value in (("w:color", "1F6F5C"), ("w:u", "single"), ("w:sz", "17")):
        element = OxmlElement(tag)
        element.set(qn("w:val"), value)
        props.append(element)
    text = OxmlElement("w:t")
    text.text = url
    run.append(props)
    run.append(text)
    link.append(run)
    paragraph._p.append(link)


def _answer(document: Document, content: Content) -> None:
    styles = {"bullet": "List Bullet", "numbered": "List Number", "heading": "Heading 2", "paragraph": None}
    for block in content.blocks:
        paragraph = document.add_paragraph(style=styles[block.kind])
        for text, bold in block.runs:
            paragraph.add_run(text).bold = bold


def _chart(document: Document, chart: AskChart | None, note: str | None) -> None:
    if chart is None:
        if note:
            document.add_paragraph().add_run(note).italic = True
        return
    document.add_heading(chart.title, level=1)
    if chart.note:
        document.add_paragraph().add_run(chart.note).italic = True
    document.add_picture(io.BytesIO(export_chart.png(chart)), width=Cm(17))
    _small(document.add_paragraph(), chart_footnote(chart))


def _figure(document: Document, number: int, figure: AskFigure) -> None:
    paragraph = document.add_paragraph()
    paragraph.add_run(f"[F{number}] ").bold = True
    paragraph.add_run(f"{figure.description}: ")
    paragraph.add_run(figure.value).bold = True
    if figure.rows:
        table = document.add_table(rows=0, cols=2)
        table.style = "Light List"
        for row in figure.rows:
            cells = table.add_row().cells
            cells[0].text, cells[1].text = row.name, row.value
            cells[1].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
    _small(document.add_paragraph(), figure_footnote(figure))


def _sources(document: Document, content: Content) -> None:
    if content.sources:
        document.add_heading("Sources", level=1)
    for number, source, provenance in content.sources:
        document.add_paragraph().add_run(f"[{number}] {source.title}").bold = True
        facts = " · ".join(str(p) for p in (source.department_name, source.document_year) if p)
        for line in (facts, provenance):
            if line:
                _small(document.add_paragraph(), line)
        for label, url in (("Original: ", source.source_url), ("Nokware's copy: ", source.ledger_url)):
            if url:
                paragraph = document.add_paragraph()
                _small(paragraph, label)
                _link(paragraph, url)


def docx(content: Content) -> bytes:
    document = Document()
    _styles(document)
    _frame(document)
    props = document.core_properties
    props.title, props.author, props.comments = f"Nokware answer: {content.question[:120]}", "Nokware (not an official AMA document)", HEADER_NOTICE
    _small(document.add_paragraph(), "YOUR QUESTION", bold=True)
    document.add_paragraph(content.question, style="Title")
    _small(document.add_paragraph(), f"Answered {content.answered}")
    document.add_heading("Answer", level=1)
    _answer(document, content)
    if content.no_information:
        document.add_paragraph(content.no_information)
    _chart(document, content.chart, content.chart_note)
    if content.figures:
        document.add_heading("Live figures", level=1)
        for number, figure in content.figures:
            _figure(document, number, figure)
        _small(document.add_paragraph(), LIVE_DATA_NOTE)
    _sources(document, content)
    out = io.BytesIO()
    document.save(out)
    return out.getvalue()
