"use client";

import { DownloadIcon } from "lucide-react";
import { useState } from "react";

import { ErrorNote } from "@/components/documents/panels";
import { Button } from "@/components/ui/button";
import { EXPORT_FAILED, EXPORT_FORMATS, ExportError, downloadAnswer } from "@/lib/ask/export";

import type { ExportFormat, ExportView } from "@/lib/api/types";

/** Download the answer as a PDF, a Word document or a CSV. Each says it's Nokware's, not an official AMA document. */
export function ExportMenu({ view, testId }: { view: ExportView; testId: string }) {
  const [busy, setBusy] = useState<ExportFormat | null>(null);
  const [error, setError] = useState<string | null>(null);
  const download = async (format: ExportFormat) => {
    setBusy(format);
    setError(null);
    try {
      await downloadAnswer(view, format);
    } catch (failure) {
      setError(failure instanceof ExportError ? failure.message : EXPORT_FAILED);
    } finally {
      setBusy(null);
    }
  };
  return (
    <div className="flex flex-col gap-2 border-t pt-4" data-testid={`${testId}-export`}>
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-[13px] text-ink-soft">Download this answer:</span>
        {EXPORT_FORMATS.map(({ format, label }) => (
          <Button key={format} variant="secondary" size="sm" disabled={busy !== null} onClick={() => download(format)} data-testid={`${testId}-export-${format}`}>
            <DownloadIcon data-icon="inline-start" />
            {busy === format ? "Preparing…" : label}
          </Button>
        ))}
      </div>
      <p className="text-[12px] text-ink-soft">Marked as generated by Nokware from the Assembly&apos;s published documents, not an official AMA document.</p>
      {error ? <ErrorNote testId={`${testId}-export-error`}>{error}</ErrorNote> : null}
    </div>
  );
}
